<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NSSoloDB</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="SoloDB" Version="1.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NS.Domain\NS.Domain.csproj" />
  </ItemGroup>

</Project>
